export const CONFIG = {
    tour_schema : {
        en_name: '',
        ru_name: '',
        images: [],
        startDateAndTime: '',
        hasGuide: true,
        duration: 0,
        languages : ['English', 'Русский'],
        en_highlights: [],
        ru_highlights: [],
        en_includes: [],
        ru_includes: [],
        en_notSuitable: [],
        ru_notSuitable: [],
        en_needed: [],
        ru_needed: [],
        availableDates: [],
        pricetForAdults: 0,
        pricetForChildren: 0,
        rate: 0,
        city: '',
        categoryId: '',
        managerId: '',
        en_fullDescription: '',
        ru_fullDescription: '',
    },
    cities : ['Sharm El Sheikh', 'Hurgada'],
};