export const CONFIG = {
    IMAGE_UPLOAD_URL: 'http://localhost:3000/v1/media/upload',
    tour_schema : {
        en_name: '',
        ru_name: '',
        images: [],
        startDateAndTime: '',
        hasGuide: true,
        duration: 0,
        languages : [],
        en_highlights: [],
        ru_highlights: [],
        en_includes: [],
        ru_includes: [],
        en_notSuitable: [],
        ru_notSuitable: [],
        en_needed: [],
        ru_needed: [],
        availableDates: [],
        priceForAdults: 0,
        priceForChildren: 0,
        // rate: 0,
        city: '',
        categoryId: '',
        managerId: '',
        en_fullDescription: '',
        ru_fullDescription: '',
    },
    category_schema: {
        en_name: '',
        ru_name: '',
        url: '',
        city: '',
    },
    blog_schema: {
        en_title: '',
        ru_title: '',
        en_description: '',
        ru_description: '',
        urls: "",
    },
    cities : ['Sharm El Sheikh', 'Hurgada', 'Aswan'],
    roles : ['manager', 'member'],
};